# Generated by Django 5.0.4 on 2024-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle')], max_length=20)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_size', models.CharField(max_length=50)),
                ('id_driving_license', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
