# Generated by Django 5.0.4 on 2024-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id_driving_license',
            field=models.IntegerField(unique=True),
        ),
    ]
