# Generated by Django 5.0.4 on 2024-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0003_alter_vehicle_max_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='max_weight',
            field=models.IntegerField(),
        ),
    ]
