# Generated by Django 5.0.4 on 2024-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0004_alter_vehicle_max_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
    ]
