# Generated by Django 5.0.4 on 2024-06-01 18:34

import vehicule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0007_alter_vehicle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=vehicule.models.vehicle_photo_path),
        ),
    ]
