# Generated by Django 5.0.4 on 2024-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0008_alter_vehicle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id_driving_license',
            field=models.IntegerField(),
        ),
    ]
