# Generated by Django 5.0.4 on 2024-04-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
