# Generated by Django 5.0.4 on 2024-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_driving_license',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
