# Generated by Django 5.0.4 on 2024-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_id_driving_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Driver', 'Driver')], default='Client', max_length=10),
        ),
    ]
