# Generated by Django 5.0.4 on 2024-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='geolocation',
            field=models.TextField(default=''),
        ),
    ]
