# Generated by Django 5.0.4 on 2024-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('iddriver', models.IntegerField(blank=True, null=True)),
                ('idclient', models.IntegerField(blank=True, null=True)),
                ('textmessage', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
