# Generated by Django 5.0.4 on 2024-05-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='textmessage',
            field=models.TextField(default='', max_length=100),
        ),
    ]
