# Generated by Django 5.0.4 on 2024-06-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_textmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='idclient',
            new_name='fromuser',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='iddriver',
            new_name='touser',
        ),
    ]
