# Generated by Django 5.0.4 on 2024-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddriver', models.IntegerField()),
                ('fromlat', models.FloatField()),
                ('fromlon', models.FloatField()),
                ('tolat', models.FloatField()),
                ('tolon', models.FloatField()),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
