# Generated by Django 5.0.4 on 2024-05-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_command_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='desqreption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='idclient',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='iddriver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
