# Generated by Django 5.0.4 on 2024-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_alter_command_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='fromlat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='fromlon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='tolat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='tolon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
